name: NodeJS Build Process

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:    

  integration:
    uses: yadickson/workflows/.github/workflows/integration.yml@v1
    secrets: inherit
